<a href="https://colab.research.google.com/github/kushalhole/Data_science_lab_SE_20/blob/main/ds_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

### Worldometer Coronavirus Summary Data

In [ ]:
summary_df = pd.read_csv('/content/worldometer_coronavirus_summary_data.csv')
display(summary_df.head())

,country,continent,total_confirmed,total_deaths,total_recovered,active_cases,serious_or_critical,total_cases_per_1m_population,total_deaths_per_1m_population,total_tests,total_tests_per_1m_population,population
0,Afghanistan,Asia,179267,7690.0,162202.0,9375.0,1124.0,4420,190.0,951337.0,23455.0,40560636
1,Albania,Europe,275574,3497.0,271826.0,251.0,2.0,95954,1218.0,1817530.0,632857.0,2871945
2,Algeria,Africa,265816,6875.0,178371.0,80570.0,6.0,5865,152.0,230861.0,5093.0,45325517
3,Andorra,Europe,42156,153.0,41021.0,982.0,14.0,543983,1974.0,249838.0,3223924.0,77495
4,Angola,Africa,99194,1900.0,97149.0,145.0,NaN,2853,55.0,1499795.0,43136.0,34769277

### Worldometer Coronavirus Daily Data

In [ ]:
daily_df = pd.read_csv('/content/worldometer_coronavirus_daily_data.csv')
display(daily_df.head())

,date,country,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
0,2020-2-15,Afghanistan,0.0,NaN,0.0,0.0,NaN
1,2020-2-16,Afghanistan,0.0,NaN,0.0,0.0,NaN
2,2020-2-17,Afghanistan,0.0,NaN,0.0,0.0,NaN
3,2020-2-18,Afghanistan,0.0,NaN,0.0,0.0,NaN
4,2020-2-19,Afghanistan,0.0,NaN,0.0,0.0,NaN

### Summary Data Overview

In [ ]:
print('--- summary_df info() ---\n')
summary_df.info()
print('\n--- summary_df describe() ---\n')
display(summary_df.describe())

--- summary_df info() ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         226 non-null    object
 1   continent                       226 non-null    object
 2   total_confirmed                 226 non-null    int64
 3   total_deaths                    218 non-null    float64
 4   total_recovered                 204 non-null    float64
 5   active_cases                    204 non-null    float64
 6   serious_or_critical             145 non-null    float64
 7   total_cases_per_1m_population   226 non-null    int64
 8   total_deaths_per_1m_population  218 non-null    float64
 9   total_tests                     212 non-null    float64
 10  total_tests_per_1m_population   212 non-null    float64
 11  population                      226 non-null    int64
dtypes: float64(7), int64(3), object(2)
memory usage: 21.3+ KB

--- summary_df describe() ---

,total_confirmed,total_deaths,total_recovered,active_cases,serious_or_critical,total_cases_per_1m_population,total_deaths_per_1m_population,total_tests,total_tests_per_1m_population,population
count,2.260000e+02,2.180000e+02,2.040000e+02,2.040000e+02,145.000000,226.000000,218.000000,2.120000e+02,2.120000e+02,2.260000e+02
mean,2.305651e+06,2.884442e+04,2.256851e+06,6.861029e+04,269.482759,148156.809735,1157.550459,2.987445e+07,1.944650e+06,3.495521e+07
std,7.575510e+06,9.971254e+04,7.613357e+06,2.350430e+05,883.174727,155202.909225,1212.833590,1.079635e+08,3.318400e+06,1.390338e+08
min,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000,16.000000,2.000000,5.117000e+03,5.093000e+03,8.050000e+02
25%,2.412600e+04,2.370000e+02,1.619300e+04,2.397500e+02,5.000000,11748.250000,172.500000,3.472968e+05,1.667260e+05,5.605125e+05
50%,1.793750e+05,2.251500e+03,1.372740e+05,1.634000e+03,17.000000,98271.500000,768.000000,2.238918e+06,7.753355e+05,5.800570e+06
75%,1.090902e+06,1.400650e+04,1.006245e+06,1.929675e+04,139.000000,255632.750000,1850.000000,1.233862e+07,2.267408e+06,2.187284e+07
max,8.420947e+07,1.026646e+06,8.124426e+07,1.938567e+06,8318.000000,704302.000000,6297.000000,1.016883e+09,2.184247e+07,1.439324e+09

### Daily Data Overview

In [ ]:
print('--- daily_df info() ---\n')
daily_df.info()
print('\n--- daily_df describe() ---\n')
display(daily_df.describe())

--- daily_df info() ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184787 entries, 0 to 184786
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date                     184787 non-null  object
 1   country                  184787 non-null  object
 2   cumulative_total_cases   184787 non-null  float64
 3   daily_new_cases          174329 non-null  float64
 4   active_cases             166747 non-null  float64
 5   cumulative_total_deaths  178227 non-null  float64
 6   daily_new_deaths         157850 non-null  float64
dtypes: float64(5), object(2)
memory usage: 9.9+ MB

--- daily_df describe() ---

,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
count,1.847870e+05,174329.000000,1.667470e+05,1.782270e+05,157850.000000
mean,7.251089e+05,2987.633285,6.239283e+04,1.388600e+04,39.831834
std,3.681471e+06,17803.232663,3.955641e+05,6.049521e+04,181.102770
min,0.000000e+00,-322.000000,-1.432100e+04,0.000000e+00,-39.000000
25%,1.099000e+03,0.000000,6.000000e+01,2.400000e+01,0.000000
50%,1.775600e+04,58.000000,1.386000e+03,3.040000e+02,1.000000
75%,2.238085e+05,728.000000,1.462050e+04,4.111000e+03,12.000000
max,8.420947e+07,909610.000000,1.793543e+07,1.026646e+06,5093.000000

### Summary Data Overview

In [ ]:
print('--- summary_df info() ---\n')
summary_df.info()
print('\n--- summary_df describe() ---\n')
display(summary_df.describe())

--- summary_df info() ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         226 non-null    object
 1   continent                       226 non-null    object
 2   total_confirmed                 226 non-null    int64
 3   total_deaths                    218 non-null    float64
 4   total_recovered                 204 non-null    float64
 5   active_cases                    204 non-null    float64
 6   serious_or_critical             145 non-null    float64
 7   total_cases_per_1m_population   226 non-null    int64
 8   total_deaths_per_1m_population  218 non-null    float64
 9   total_tests                     212 non-null    float64
 10  total_tests_per_1m_population   212 non-null    float64
 11  population                      226 non-null    int64
dtypes: float64(7), int64(3), object(2)
memory usage: 21.3+ KB

--- summary_df describe() ---

,total_confirmed,total_deaths,total_recovered,active_cases,serious_or_critical,total_cases_per_1m_population,total_deaths_per_1m_population,total_tests,total_tests_per_1m_population,population
count,2.260000e+02,2.180000e+02,2.040000e+02,2.040000e+02,145.000000,226.000000,218.000000,2.120000e+02,2.120000e+02,2.260000e+02
mean,2.305651e+06,2.884442e+04,2.256851e+06,6.861029e+04,269.482759,148156.809735,1157.550459,2.987445e+07,1.944650e+06,3.495521e+07
std,7.575510e+06,9.971254e+04,7.613357e+06,2.350430e+05,883.174727,155202.909225,1212.833590,1.079635e+08,3.318400e+06,1.390338e+08
min,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000,16.000000,2.000000,5.117000e+03,5.093000e+03,8.050000e+02
25%,2.412600e+04,2.370000e+02,1.619300e+04,2.397500e+02,5.000000,11748.250000,172.500000,3.472968e+05,1.667260e+05,5.605125e+05
50%,1.793750e+05,2.251500e+03,1.372740e+05,1.634000e+03,17.000000,98271.500000,768.000000,2.238918e+06,7.753355e+05,5.800570e+06
75%,1.090902e+06,1.400650e+04,1.006245e+06,1.929675e+04,139.000000,255632.750000,1850.000000,1.233862e+07,2.267408e+06,2.187284e+07
max,8.420947e+07,1.026646e+06,8.124426e+07,1.938567e+06,8318.000000,704302.000000,6297.000000,1.016883e+09,2.184247e+07,1.439324e+09

### Daily Data Overview

In [ ]:
print('--- daily_df info() ---\n')
daily_df.info()
print('\n--- daily_df describe() ---\n')
display(daily_df.describe())

--- daily_df info() ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184787 entries, 0 to 184786
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date                     184787 non-null  object
 1   country                  184787 non-null  object
 2   cumulative_total_cases   184787 non-null  float64
 3   daily_new_cases          174329 non-null  float64
 4   active_cases             166747 non-null  float64
 5   cumulative_total_deaths  178227 non-null  float64
 6   daily_new_deaths         157850 non-null  float64
dtypes: float64(5), object(2)
memory usage: 9.9+ MB

--- daily_df describe() ---

,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
count,1.847870e+05,174329.000000,1.667470e+05,1.782270e+05,157850.000000
mean,7.251089e+05,2987.633285,6.239283e+04,1.388600e+04,39.831834
std,3.681471e+06,17803.232663,3.955641e+05,6.049521e+04,181.102770
min,0.000000e+00,-322.000000,-1.432100e+04,0.000000e+00,-39.000000
25%,1.099000e+03,0.000000,6.000000e+01,2.400000e+01,0.000000
50%,1.775600e+04,58.000000,1.386000e+03,3.040000e+02,1.000000
75%,2.238085e+05,728.000000,1.462050e+04,4.111000e+03,12.000000
max,8.420947e+07,909610.000000,1.793543e+07,1.026646e+06,5093.000000

### Data Cleaning: `daily_df`

In [ ]:
# Convert 'date' column to datetime objects
daily_df['date'] = pd.to_datetime(daily_df['date'])

# Replace negative daily_new_cases with 0
daily_df['daily_new_cases'] = daily_df['daily_new_cases'].apply(lambda x: max(0, x))

# Replace negative daily_new_deaths with 0
daily_df['daily_new_deaths'] = daily_df['daily_new_deaths'].apply(lambda x: max(0, x))

print('--- daily_df info() after cleaning ---\n')
daily_df.info()
print('\n--- daily_df describe() after cleaning ---\n')
display(daily_df.describe())

--- daily_df info() after cleaning ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184787 entries, 0 to 184786
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date                     184787 non-null  datetime64[ns]
 1   country                  184787 non-null  object
 2   cumulative_total_cases   184787 non-null  float64
 3   daily_new_cases          184787 non-null  float64
 4   active_cases             166747 non-null  float64
 5   cumulative_total_deaths  178227 non-null  float64
 6   daily_new_deaths         184787 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 9.9+ MB

--- daily_df describe() after cleaning ---

,date,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
count,184787,1.847870e+05,184787.000000,1.667470e+05,1.782270e+05,184787.000000
mean,2021-03-30 20:11:51.556549120,7.251089e+05,2818.556019,6.239283e+04,1.388600e+04,34.025862
min,2020-01-22 00:00:00,0.000000e+00,0.000000,-1.432100e+04,0.000000e+00,0.000000
25%,2020-09-07 00:00:00,1.099000e+03,0.000000,6.000000e+01,2.400000e+01,0.000000
50%,2021-03-31 00:00:00,1.775600e+04,41.000000,1.386000e+03,3.040000e+02,0.000000
75%,2021-10-22 00:00:00,2.238085e+05,636.000000,1.462050e+04,4.111000e+03,8.000000
max,2022-05-14 00:00:00,8.420947e+07,909610.000000,1.793543e+07,1.026646e+06,5093.000000
std,NaN,3.681471e+06,17305.880211,3.955641e+05,6.049521e+04,167.972047

### Data Cleaning: `daily_df`

In [ ]:
# Convert 'date' column to datetime objects
daily_df['date'] = pd.to_datetime(daily_df['date'])

# Replace negative daily_new_cases with 0
daily_df['daily_new_cases'] = daily_df['daily_new_cases'].apply(lambda x: max(0, x))

# Replace negative daily_new_deaths with 0
daily_df['daily_new_deaths'] = daily_df['daily_new_deaths'].apply(lambda x: max(0, x))

# Replace negative active_cases with 0
daily_df['active_cases'] = daily_df['active_cases'].apply(lambda x: max(0, x))

print('--- daily_df info() after cleaning ---\n')
daily_df.info()
print('\n--- daily_df describe() after cleaning ---\n')
display(daily_df.describe())

--- daily_df info() after cleaning ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184787 entries, 0 to 184786
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date                     184787 non-null  datetime64[ns]
 1   country                  184787 non-null  object
 2   cumulative_total_cases   184787 non-null  float64
 3   daily_new_cases          184787 non-null  float64
 4   active_cases             184787 non-null  float64
 5   cumulative_total_deaths  178227 non-null  float64
 6   daily_new_deaths         184787 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 9.9+ MB

--- daily_df describe() after cleaning ---

,date,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
count,184787,1.847870e+05,184787.000000,1.847870e+05,1.782270e+05,184787.000000
mean,2021-03-30 20:11:51.556549120,7.251089e+05,2818.556019,5.631106e+04,1.388600e+04,34.025862
min,2020-01-22 00:00:00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000
25%,2020-09-07 00:00:00,1.099000e+03,0.000000,9.000000e+00,2.400000e+01,0.000000
50%,2021-03-31 00:00:00,1.775600e+04,41.000000,8.110000e+02,3.040000e+02,0.000000
75%,2021-10-22 00:00:00,2.238085e+05,636.000000,1.147900e+04,4.111000e+03,8.000000
max,2022-05-14 00:00:00,8.420947e+07,909610.000000,1.793543e+07,1.026646e+06,5093.000000
std,NaN,3.681471e+06,17305.880211,3.762141e+05,6.049521e+04,167.972047